tool
extends TileMap

const PLAIN_PERCENTAGE : = 0.85 # percent of autogenerated tiles that are plain

export var tile_position = Vector2(0, 0)
export var tile_size = Vector2(300, 300)


func _ready():
	if Engine.editor_hint:
		_autogenerate_tiles()


func _autogenerate_tiles():
	for x in tile_size.x:
		for y in tile_size.y:
			var cell : int = 0
			randomize()
			var random = randf()
			if random <= PLAIN_PERCENTAGE:
				cell = 0
			else:
				cell = randi()%9 + 1
			set_cell(x + tile_position.x, y + tile_position.y, cell)

